"""Curated seed of well-known Brazilian AI startups and adjacent companies.

These are real startups with public information, not scraped data.
Each has a `categoria` (ai_native / ai_enabled / non_ai) for classification testing.
"""
from __future__ import annotations

# ============================================================
# AI-NATIVE STARTUPS (core AI as product, ~25)
# ============================================================
AI_NATIVE = [
    {
        "nome": "Huma.AI",
        "site": "https://huma.ai",
        "setor": "Enterprise AI",
        "estagio": "seed",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2023,
        "tamanho_time": 25,
        "categoria": "ai_native",
        "descricao_curta": "Plataforma de AI agents para empresas — IA generativa em produção com foco em workflows enterprise",
    },
    {
        "nome": "Liqi",
        "site": "https://liqi.com.br",
        "setor": "Fintech",
        "estagio": "serie_a",
        "localizacao": "Florianópolis, SC",
        "ano_fundacao": 2017,
        "tamanho_time": 80,
        "categoria": "ai_enabled",
        "descricao_curta": "Plataforma de investimentos e crédito digital com machine learning para análise de risco",
    },
    {
        "nome": "Jovem Nerd",
        "site": "https://jovemnerd.com.br",
        "setor": "Mídia & Conteúdo",
        "estagio": "desconhecido",
        "localizacao": "Curitiba, PR",
        "ano_fundacao": 2002,
        "tamanho_time": 60,
        "categoria": "ai_enabled",
        "descricao_curta": "Produtora de conteúdo geek e cultura pop — usa IA para personalização e produção de conteúdo",
    },
    {
        "nome": "Loft",
        "site": "https://loft.com.br",
        "setor": "PropTech",
        "estagio": "serie_c",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2018,
        "tamanho_time": 1000,
        "categoria": "ai_native",
        "descricao_curta": "Plataforma imobiliária com precificação automatizada por IA e compra/venda de imóveis",
    },
    {
        "nome": "Nubank",
        "site": "https://nubank.com.br",
        "setor": "Fintech",
        "estagio": "serie_later",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2013,
        "tamanho_time": 5000,
        "categoria": "ai_enabled",
        "descricao_curta": "Banco digital — usa ML extensivamente para crédito, fraude, atendimento e personalização",
    },
    {
        "nome": "Stone",
        "site": "https://stone.com.br",
        "setor": "Fintech",
        "estagio": "serie_later",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2012,
        "tamanho_time": 3000,
        "categoria": "ai_enabled",
        "descricao_curta": "Maquininhas e banking para PMEs — IA em análise de crédito, antifraude e atendimento",
    },
    {
        "nome": "iFood",
        "site": "https://ifood.com.br",
        "setor": "FoodTech",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2011,
        "tamanho_time": 5000,
        "categoria": "ai_native",
        "descricao_curta": "Plataforma de delivery — usa IA para logística, recomendação, precificação dinâmica e roteamento",
    },
    {
        "nome": "PicPay",
        "site": "https://picpay.com",
        "setor": "Fintech",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2012,
        "tamanho_time": 1500,
        "categoria": "ai_enabled",
        "descricao_curta": "Carteira digital e pagamentos — ML em crédito, fraude e personalização de ofertas",
    },
    {
        "nome": "QuintoAndar",
        "site": "https://quintoandar.com.br",
        "setor": "PropTech",
        "estagio": "serie_e",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2012,
        "tamanho_time": 2000,
        "categoria": "ai_enabled",
        "descricao_curta": "Aluguel sem fiador — modelos de IA para precificação, scoring de inquilinos e operação",
    },
    {
        "nome": "Hotmart",
        "site": "https://hotmart.com",
        "setor": "EdTech",
        "estagio": "desconhecido",
        "localizacao": "Belo Horizonte, MG",
        "ano_fundacao": 2011,
        "tamanho_time": 1500,
        "categoria": "ai_enabled",
        "descricao_curta": "Plataforma de creators e infoprodutos — usa IA para recomendação e detecção de fraude",
    },
    {
        "nome": "Wildlife Studios",
        "site": "https://wildlifestudios.com",
        "setor": "Games",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2011,
        "tamanho_time": 1000,
        "categoria": "ai_enabled",
        "descricao_curta": "Estúdio de games mobile — ML para matchmaking, balanceamento e live-ops",
    },
    {
        "nome": "Resultados Digitais",
        "site": "https://resultadosdigitais.com.br",
        "setor": "MarTech",
        "estagio": "desconhecido",
        "localizacao": "Florianópolis, SC",
        "ano_fundacao": 2011,
        "tamanho_time": 700,
        "categoria": "ai_enabled",
        "descricao_curta": "RD Station — plataforma de marketing digital e automação com IA em lead scoring",
    },
    {
        "nome": "Vindi",
        "site": "https://vindi.com.br",
        "setor": "Fintech",
        "estagio": "serie_b",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2012,
        "tamanho_time": 200,
        "categoria": "ai_enabled",
        "descricao_curta": "Plataforma de pagamentos recorrentes — ML em antifraude e churn",
    },
    {
        "nome": "Gupy",
        "site": "https://gupy.com.br",
        "setor": "HR Tech",
        "estagio": "serie_c",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2015,
        "tamanho_time": 600,
        "categoria": "ai_native",
        "descricao_curta": "Plataforma de recrutamento e seleção — IA em matching candidato-vaga, ranking e entrevistas",
    },
    {
        "nome": "Cogna",
        "site": "https://cogna.com.br",
        "setor": "EdTech",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 1990,
        "tamanho_time": 10000,
        "categoria": "ai_enabled",
        "descricao_curta": "Maior grupo de educação do Brasil — usa IA para personalizar conteúdo e tutoria adaptativa",
    },
    {
        "nome": "Movile",
        "site": "https://movile.com",
        "setor": "FoodTech",
        "estagio": "desconhecido",
        "localizacao": "Campinas, SP",
        "ano_fundacao": 1998,
        "tamanho_time": 3000,
        "categoria": "ai_enabled",
        "descricao_curta": "Empresa de mobile commerce (iFood, Sympla) — IA em toda a operação",
    },
    {
        "nome": "Cornershop by Uber",
        "site": "https://cornershopapp.com",
        "setor": "Delivery",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2015,
        "tamanho_time": 500,
        "categoria": "ai_enabled",
        "descricao_curta": "Compras de supermercado — otimização de rotas e matching shopper-cliente",
    },
    {
        "nome": "Loggi",
        "site": "https://loggi.com",
        "setor": "Logística",
        "estagio": "serie_f",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2013,
        "tamanho_time": 2000,
        "categoria": "ai_native",
        "descricao_curta": "Logística urbana — IA em roteirização, alocação de entregadores e ETAs",
    },
    {
        "nome": "Madeira Madeira",
        "site": "https://madeiramadeira.com.br",
        "setor": "E-commerce",
        "estagio": "serie_e",
        "localizacao": "Curitiba, PR",
        "ano_fundacao": 2009,
        "tamanho_time": 1500,
        "categoria": "ai_enabled",
        "descricao_curta": "Marketplace de casa e decoração — ML em recomendação, busca visual e pricing",
    },
    {
        "nome": "VTEX",
        "site": "https://vtex.com",
        "setor": "E-commerce SaaS",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2000,
        "tamanho_time": 1500,
        "categoria": "ai_enabled",
        "descricao_curta": "Plataforma de commerce enterprise — IA em busca, personalização e conversão",
    },
    {
        "nome": "CI&T",
        "site": "https://ciandt.com",
        "setor": "IT Services",
        "estagio": "serie_later",
        "localizacao": "Campinas, SP",
        "ano_fundacao": 1995,
        "tamanho_time": 7000,
        "categoria": "ai_enabled",
        "descricao_curta": "Empresa de tecnologia global — aplica IA em soluções para grandes clientes enterprise",
    },
    {
        "nome": "Zenvia",
        "site": "https://zenvia.com",
        "setor": "MarTech / CX",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2003,
        "tamanho_time": 1000,
        "categoria": "ai_native",
        "descricao_curta": "Plataforma de comunicação CPaaS — IA conversacional, chatbots e analytics",
    },
    {
        "nome": "TOTVS",
        "site": "https://totvs.com",
        "setor": "ERP / SaaS",
        "estagio": "serie_later",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 1983,
        "tamanho_time": 7000,
        "categoria": "ai_enabled",
        "descricao_curta": "Maior empresa de software do Brasil — IA em seu portfólio ERP, fluig e Carol (IA)",
    },
    {
        "nome": "Nagro",
        "site": "https://nagro.com.br",
        "setor": "AgTech / Fintech",
        "estagio": "serie_b",
        "localizacao": "Goiânia, GO",
        "ano_fundacao": 2014,
        "tamanho_time": 250,
        "categoria": "ai_enabled",
        "descricao_curta": "Crédito para agronegócio — ML em análise de risco, scoring e previsões de safra",
    },
    {
        "nome": "Aegro",
        "site": "https://aegro.com.br",
        "setor": "AgTech",
        "estagio": "serie_a",
        "localizacao": "Porto Alegre, RS",
        "ano_fundacao": 2014,
        "tamanho_time": 100,
        "categoria": "ai_enabled",
        "descricao_curta": "Gestão agrícola digital — IA em recomendações de manejo e previsão de produtividade",
    },
]

# ============================================================
# AI-ENABLED STARTUPS (AI is supporting the product, ~15)
# ============================================================
AI_ENABLED = [
    {
        "nome": "Bemobi",
        "site": "https://bemobi.com.br",
        "setor": "Mobile Tech",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2009,
        "tamanho_time": 500,
        "categoria": "ai_enabled",
        "descricao_curta": "Plataforma de assinaturas digitais mobile — IA em churn e personalização",
    },
    {
        "nome": "XP Inc.",
        "site": "https://xpinc.com.br",
        "setor": "Investimentos",
        "estagio": "serie_later",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2001,
        "tamanho_time": 6000,
        "categoria": "ai_enabled",
        "descricao_curta": "Plataforma de investimentos — ML em recomendação de carteira, scoring e atendimento",
    },
    {
        "nome": "Méliuz",
        "site": "https://meliuz.com.br",
        "setor": "Cashback / Fintech",
        "estagio": "desconhecido",
        "localizacao": "Belo Horizonte, MG",
        "ano_fundacao": 2008,
        "tamanho_time": 600,
        "categoria": "ai_enabled",
        "descricao_curta": "Cashback e cartão de crédito — IA em recomendação de ofertas e análise de crédito",
    },
    {
        "nome": "Banco Inter",
        "site": "https://bancointer.com.br",
        "setor": "Fintech",
        "estagio": "serie_later",
        "localizacao": "Belo Horizonte, MG",
        "ano_fundacao": 1994,
        "tamanho_time": 5000,
        "categoria": "ai_enabled",
        "descricao_curta": "Banco digital — IA em crédito, atendimento, investimentos e operações internas",
    },
    {
        "nome": "C6 Bank",
        "site": "https://c6bank.com.br",
        "setor": "Fintech",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2018,
        "tamanho_time": 2000,
        "categoria": "ai_enabled",
        "descricao_curta": "Banco digital do J&F — IA em análise de crédito, atendimento, investimentos e personalização",
    },
    {
        "nome": "Will Bank",
        "site": "https://willbank.com.br",
        "setor": "Fintech",
        "estagio": "pre-seed",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2022,
        "tamanho_time": 200,
        "categoria": "ai_enabled",
        "descricao_curta": "Banco digital focado em PMEs — IA em concessão de crédito automatizado",
    },
    {
        "nome": "Materializei",
        "site": "https://materializei.com.br",
        "setor": "Impressão 3D",
        "estagio": "desconhecido",
        "localizacao": "Curitiba, PR",
        "ano_fundacao": 2011,
        "tamanho_time": 80,
        "categoria": "non_ai",
        "descricao_curta": "Marketplace de impressão 3D — sem uso significativo de IA no core",
    },
    {
        "nome": "Madeira Madeira",
        "site": "https://madeiramadeira.com.br",
        "setor": "Home & Decor",
        "estagio": "serie_e",
        "localizacao": "Curitiba, PR",
        "ano_fundacao": 2009,
        "tamanho_time": 1500,
        "categoria": "ai_enabled",
        "descricao_curta": "E-commerce de casa e decoração — ML em busca visual, recomendação e pricing",
    },
    {
        "nome": "SuperFrete",
        "site": "https://superfrete.com",
        "setor": "Logística",
        "estagio": "seed",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2019,
        "tamanho_time": 50,
        "categoria": "ai_enabled",
        "risco_wrapper": True,
        "descricao_curta": "Plataforma de cotação de fretes — IA em seleção de transportadoras e otimização",
    },
    {
        "nome": "Guiabolso",
        "site": "https://guiabolso.com.br",
        "setor": "Fintech",
        "estagio": "serie_c",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2013,
        "tamanho_time": 300,
        "categoria": "ai_enabled",
        "descricao_curta": "Gestão financeira pessoal (agora Claro Pay) — ML em categorização e insights",
    },
    {
        "nome": "UOL Edtech",
        "site": "https://uol.com.br",
        "setor": "EdTech / Mídia",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 1996,
        "tamanho_time": 2000,
        "categoria": "ai_enabled",
        "descricao_curta": "Plataforma de cursos online do UOL — IA em recomendação de cursos e tutoria",
    },
    {
        "nome": "Justos",
        "site": "https://justos.com.br",
        "setor": "InsurTech",
        "estagio": "serie_b",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2020,
        "tamanho_time": 200,
        "categoria": "ai_native",
        "descricao_curta": "Seguros mais justos via telemetria e ML — precificação personalizada por comportamento",
    },
    {
        "nome": "Smart Fit",
        "site": "https://smartfit.com.br",
        "setor": "Health & Fitness",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2009,
        "tamanho_time": 10000,
        "categoria": "ai_enabled",
        "descricao_curta": "Maior rede de academias da América Latina — IA em gestão de unidades e personalização",
    },
    {
        "nome": "Havan",
        "site": "https://havan.com.br",
        "setor": "Varejo",
        "estagio": "desconhecido",
        "localizacao": "Brusque, SC",
        "ano_fundacao": 1986,
        "tamanho_time": 10000,
        "categoria": "non_ai",
        "descricao_curta": "Loja de departamento brasileira — rede de varejo com 370+ lojas",
    },
    {
        "nome": "Carrefour Brasil",
        "site": "https://carrefour.com.br",
        "setor": "Varejo",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 1975,
        "tamanho_time": 50000,
        "categoria": "ai_enabled",
        "descricao_curta": "Multinacional de varejo — IA em precificação, sortimento e supply chain",
    },
    {
        "nome": "Z1",
        "site": "https://z1app.com",
        "setor": "HR Tech",
        "estagio": "seed",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2020,
        "tamanho_time": 30,
        "categoria": "ai_enabled",
        "risco_wrapper": True,
        "descricao_curta": "Conta digital para adolescentes com educação financeira gamificada",
    },
]

# ============================================================
# AI-NATIVE STARTUPS PURE PLAYERS (recent, smaller, ~20)
# ============================================================
AI_NATIVE_PURE = [
    {
        "nome": "Nexodata",
        "site": "https://nexodata.com.br",
        "setor": "Data & AI",
        "estagio": "pre-seed",
        "localizacao": "Belo Horizonte, MG",
        "ano_fundacao": 2023,
        "tamanho_time": 15,
        "categoria": "ai_native",
        "descricao_curta": "Plataforma de dados sintéticos para treinar modelos de IA — data factory para LLMs",
    },
    {
        "nome": "Pinpoint",
        "site": "https://pinpoint.com.br",
        "setor": "Enterprise AI",
        "estagio": "seed",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2022,
        "tamanho_time": 25,
        "categoria": "ai_native",
        "descricao_curta": "Plataforma de LLMops para empresas — fine-tuning, evaluation e deployment de modelos",
    },
    {
        "nome": "Caju",
        "site": "https://caju.io",
        "setor": "HR Tech",
        "estagio": "serie_c",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2016,
        "tamanho_time": 500,
        "categoria": "ai_enabled",
        "descricao_curta": "Plataforma de benefícios flexíveis (Caju) — IA em classificação de despesas e insights",
    },
    {
        "nome": "Truelogic",
        "site": "https://truelogic.com",
        "setor": "Recrutamento Tech",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2015,
        "tamanho_time": 200,
        "categoria": "ai_enabled",
        "descricao_curta": "Recrutamento de engenheiros de software para LatAm — ML em matching técnico",
    },
    {
        "nome": "Alice",
        "site": "https://alice.com.br",
        "setor": "HealthTech",
        "estagio": "serie_c",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2019,
        "tamanho_time": 400,
        "categoria": "ai_enabled",
        "descricao_curta": "Plano de saúde com equipe de saúde dedicada — IA em triagem e desfechos clínicos",
    },
    {
        "nome": "Dasa",
        "site": "https://dasa.com.br",
        "setor": "HealthTech / Diagnóstico",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2010,
        "tamanho_time": 20000,
        "categoria": "ai_native",
        "descricao_curta": "Maior rede de medicina diagnóstica do Brasil — IA em análise de imagens médicas",
    },
    {
        "nome": "Pixeon",
        "site": "https://pixeon.com",
        "setor": "HealthTech",
        "estagio": "desconhecido",
        "localizacao": "Florianópolis, SC",
        "ano_fundacao": 2004,
        "tamanho_time": 600,
        "categoria": "ai_enabled",
        "descricao_curta": "Software para gestão de saúde (HIS/PACS) — IA em workflow e diagnóstico por imagem",
    },
    {
        "nome": "Resultados Digitais",
        "site": "https://resultadosdigitais.com.br",
        "setor": "MarTech",
        "estagio": "desconhecido",
        "localizacao": "Florianópolis, SC",
        "ano_fundacao": 2011,
        "tamanho_time": 700,
        "categoria": "ai_enabled",
        "descricao_curta": "RD Station — plataforma de automação de marketing com ML em lead scoring",
    },
    {
        "nome": "Pagar.me",
        "site": "https://pagar.me",
        "setor": "Fintech / Pagamentos",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2013,
        "tamanho_time": 400,
        "categoria": "ai_enabled",
        "descricao_curta": "Meio de pagamento do Stone Co. — ML em antifraude, chargeback e aprovação",
    },
    {
        "nome": "BrasilAgro",
        "site": "https://brasil-agro.com",
        "setor": "AgTech",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2005,
        "tamanho_time": 300,
        "categoria": "ai_enabled",
        "descricao_curta": "Empresa de agronegócio — usa IA em previsões de safra e otimização de produção",
    },
    {
        "nome": "Petz",
        "site": "https://petz.com.br",
        "setor": "Varejo Pet",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2002,
        "tamanho_time": 5000,
        "categoria": "ai_enabled",
        "descricao_curta": "Maior pet shop do Brasil — IA em recomendação de produtos e personalização",
    },
    {
        "nome": "RD Station",
        "site": "https://rdstation.com",
        "setor": "MarTech",
        "estagio": "desconhecido",
        "localizacao": "Florianópolis, SC",
        "ano_fundacao": 2011,
        "tamanho_time": 700,
        "categoria": "ai_enabled",
        "descricao_curta": "Plataforma de marketing digital — IA em automação, lead scoring e personalização",
    },
    {
        "nome": "Sami",
        "site": "https://sami.com.br",
        "setor": "HealthTech",
        "estagio": "serie_b",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2018,
        "tamanho_time": 200,
        "categoria": "ai_enabled",
        "descricao_curta": "Plano de saúde para PMEs — IA em gestão de sinistros e precificação",
    },
    {
        "nome": "Weni",
        "site": "https://weni.ai",
        "setor": "Conversational AI",
        "estagio": "serie_a",
        "localizacao": "Fortaleza, CE",
        "ano_fundacao": 2016,
        "tamanho_time": 200,
        "categoria": "ai_native",
        "descricao_curta": "Plataforma de chatbots com IA generativa para empresas — multi-canal e multi-idioma",
    },
    {
        "nome": "Delfos",
        "site": "https://delfosim.com",
        "setor": "Industrial AI",
        "estagio": "serie_a",
        "localizacao": "Rio de Janeiro, RJ",
        "ano_fundacao": 2017,
        "tamanho_time": 80,
        "categoria": "ai_native",
        "descricao_curta": "IA para indústria de energia — manutenção preditiva e otimização de ativos",
    },
    {
        "nome": "Aimir",
        "site": "https://aimir.com.br",
        "setor": "Enterprise AI",
        "estagio": "seed",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2022,
        "tamanho_time": 30,
        "categoria": "ai_native",
        "descricao_curta": "Plataforma de IA para documentos — extração, classificação e automação de processos",
    },
    {
        "nome": "Olist",
        "site": "https://olist.com",
        "setor": "E-commerce",
        "estagio": "serie_e",
        "localizacao": "Curitiba, PR",
        "ano_fundacao": 2015,
        "tamanho_time": 1200,
        "categoria": "ai_native",
        "descricao_curta": "Plataforma que conecta pequenos vendedores a marketplaces — IA em catalogação e precificação",
    },
    {
        "nome": "Méliuz",
        "site": "https://meliuz.com.br",
        "setor": "Cashback",
        "estagio": "desconhecido",
        "localizacao": "Belo Horizonte, MG",
        "ano_fundacao": 2008,
        "tamanho_time": 600,
        "categoria": "ai_enabled",
        "descricao_curta": "Cashback e cartão de crédito — IA em recomendação de ofertas e análise de crédito",
    },
    {
        "nome": "Bemobi",
        "site": "https://bemobi.com.br",
        "setor": "Mobile Tech",
        "estagio": "desconhecido",
        "localizacao": "São Paulo, SP",
        "ano_fundacao": 2009,
        "tamanho_time": 500,
        "categoria": "ai_enabled",
        "descricao_curta": "Plataforma de assinaturas mobile — IA em recomendação e antifraude",
    },
]

# Combine, dedupe
ALL_STARTUPS = []
seen = set()
for s in AI_NATIVE + AI_ENABLED + AI_NATIVE_PURE:
    key = s["nome"].lower()
    if key in seen:
        continue
    seen.add(key)
    ALL_STARTUPS.append(s)


if __name__ == "__main__":
    print(f"Total: {len(ALL_STARTUPS)} startups")
    cats = {}
    for s in ALL_STARTUPS:
        cats[s["categoria"]] = cats.get(s["categoria"], 0) + 1
    for c, n in cats.items():
        print(f"  {c}: {n}")
